ccflags-y := 	-Wall					\
		-Wextra					\
		-Wno-missing-field-initializers		\
		-Wno-unused-parameter			\
		-Wformat				\
		-std=gnu18				\
		-g					\
		-Werror=format-security			\
		-Werror=implicit-function-declaration   \
		-DDEBUG 	\

obj-m := lsbdd.o

ifeq ($(type), lf)
	DIR := utils/lock-free
ifeq ($(type), sy)
	DIR := utils/sync
else 
	$(error Invalid type specified. Use "make type=lf" or "make type=sy")
endif

# Add dynamical include path for the ds-control headers.
ccflags-y += -I$(PWD)/$(DIR)

lsbdd-objs := main.o ds-control.o \
              $(DIR)/btree-utils.o $(DIR)/skiplist.o \
              $(DIR)/hashtable-utils.o $(DIR)/rbtree.o
