name: Linters Check

on:
  pull_request:
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.py'
      - '**/*.sh'
      - '.github/workflows/lint.yml' 
  push:
    paths: 
      - '**/*.c'
      - '**/*.h'
      - '**/*.py'
      - '**/*.sh'
      - '.github/workflows/linters.yml' # Или имя этого файла
  workflow_dispatch: 

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Download checkpatch.pl
      run: |
        curl -L -o checkpatch.pl https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl
        chmod +x ./checkpatch.pl
        perl --version
        ./checkpatch.pl --version

    - name: Run checkpatch.pl on C/H files
      run: |
        find . \( -name '*.c' -o -name '*.h' \) -print0 | \
        xargs -0 -n1 --no-run-if-empty ./checkpatch.pl --no-tree 
        # Warning: checkpatch should be executable and placed in current dir (./checkpatch.pl)

    - name: Set up Python and install Black
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Check Python code formatting with Black
      run: |
        black --check .

    - name: Install ShellCheck
      run: |
        sudo apt-get update 
        sudo apt-get install -y shellcheck

    - name: ShellCheck for shell scripts
      run: |
        find . -name '*.sh' -exec shellcheck {} +
